name: Deploy

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - uses: actions/checkout@v4

      - name: Use Node 22
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: npm ci

      - name: Vercel Pull
        run: npx vercel pull --yes --environment=production --token ${{ secrets.VERCEL_TOKEN }}

      - name: Vercel Build
        run: npx vercel build --prod --token ${{ secrets.VERCEL_TOKEN }}

      - name: Vercel Deploy
        run: npx vercel deploy --prebuilt --prod --token ${{ secrets.VERCEL_TOKEN }}
